services:
  cassandra-0:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cassandra_01
    restart: always
    volumes:
      - ./cassandra_01:/var/lib/cassandra
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=2048M
    networks:
      brgnet:
      clusternet:
        ipv4_address: 192.168.1.200

  cassandra-1:
    image: cassandra:latest
    container_name: cassandra_02
    restart: always
    volumes:
      - ./cassandra_02:/var/lib/cassandra
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=2048M
    networks:
      clusternet:
        ipv4_address: 192.168.1.201

  cassandra-2:
    image: cassandra:latest
    container_name: cassandra_03
    restart: always
    volumes:
      - ./cassandra_03:/var/lib/cassandra
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=2048M
    networks:
      clusternet:
        ipv4_address: 192.168.1.202

networks:
  clusternet:
    driver: ipvlan
    driver_opts:
      ipvlan_mode: l2
      parent: enp0s8
    ipam:
      config:
      - subnet: 192.168.1.0/24
        gateway: 192.168.1.1
  brgnet:
    driver: bridge